### ISSUE TITLE
Please add the versions of packages used. im having issue with numpy version!!

### ISSUE THREAD

**Issue by Singireddysai** [98mxr/GMFSS_Fortuna#9]

**Comment by 98mxr** [comment]
I updated the file and now cupy shouldn't report an error.
I just reinstalled the environment and confirmed that there is no need to specify a certain version of wheel for the time being.

**Comment by xmxhuihui** [comment]
@98mxr 
> I updated the file and now cupy shouldn't report an error. I just reinstalled the environment and confirmed that there is no need to specify a certain version of wheel for the time being.

Nope, I think that is because you have cache package files on your system. But I have encounered such errors.

```bash
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts
google-api-core 2.11.0 requires google-auth<3.0dev,>=2.14.1, which is not installed.
google-api-core 2.11.0 requires googleapis-common-protos<2.0dev,>=1.56.2, which is not installed.
google-api-core 2.11.0 requires requests<3.0.0dev,>=2.18.0, which is not installed.
google-api-python-client 2.81.0 requires google-auth<3.0.0dev,>=1.19.0, which is not installed.
google-api-python-client 2.81.0 requires uritemplate<5,>=3.0.1, which is not installed.
google-auth-httplib2 0.1.0 requires google-auth, which is not installed.
kaggle 1.5.13 requires certifi, which is not installed.
kaggle 1.5.13 requires requests, which is not installed.
kaggle 1.5.13 requires urllib3, which is not installed.
oauth2client 4.1.3 requires pyasn1>=0.1.7, which is not installed.
oauth2client 4.1.3 requires pyasn1-modules>=0.0.5, which is not installed.
oauth2client 4.1.3 requires rsa>=3.1.4, which is not installed.
sacrebleu 2.2.0 requires regex, which is not installed.
sacrebleu 2.2.0 requires tabulate>=0.8.9, which is not installed.
seqeval 1.2.2 requires scikit-learn>=0.21.3, which is not installed.
tensorflow-addons 0.19.0 requires typeguard>=2.7, which is not installed.
tf-models-official 2.10.1 requires Cython, which is not installed.
tf-models-official 2.10.1 requires gin-config, which is not installed.
tf-models-official 2.10.1 requires opencv-python-headless, which is not installed.
tf-models-official 2.10.1 requires pandas>=0.22.0, which is not installed.
tf-models-official 2.10.1 requires psutil>=5.4.3, which is not installed.
tf-models-official 2.10.1 requires py-cpuinfo>=3.3.0, which is not installed.
tf-models-official 2.10.1 requires pycocotools, which is not installed.
tf-models-official 2.10.1 requires pyyaml<6.0,>=5.1, which is not installed.
tf-models-official 2.10.1 requires sentencepiece, which is not installed.
tf-models-official 2.10.1 requires tensorflow~=2.10.0, which is not installed.
tf-models-official 2.10.1 requires tensorflow-datasets, which is not installed.
tf-models-official 2.10.1 requires tensorflow-hub>=0.6.0, which is not installed.
tf-models-official 2.10.1 requires tensorflow-model-optimization>=0.4.1, which is not installed.
tf-models-official 2.10.1 requires tf-slim>=1.1.0, which is not installed.
google-api-core 2.11.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 6.33.4 which is incompatible.
```
For my environment with CUDA 11.8, it installed all latest packages. For example, it automatically installed with numpy==2.0.2, but running the video_inference.py will report this error.
```bash
Traceback (most recent call last):
  File "E:\Jupyter_Notebook_Workspace\GMFSS_Fortuna\inference_video.py", line 122, in <module>
    lastframe = next(videogen)
  File "D:\anaconda3\envs\GMFSS\lib\site-packages\skvideo\io\io.py", line 251, in vreader
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "D:\anaconda3\envs\GMFSS\lib\site-packages\skvideo\io\ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "D:\anaconda3\envs\GMFSS\lib\site-packages\skvideo\io\abstract.py", line 87, in __init__
    if np.float(parts[1]) == 0.:
  File "D:\anaconda3\envs\GMFSS\lib\site-packages\numpy\__init__.py", line 424, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
So probably the version for packages are needed. Please see if you can update the requirements.txt.

**Comment by xmxhuihui** [comment]
```bash
pip install numpy==1.22.4
```
This version works fine. I have tried some others but reported errors.

**Comment by 98mxr** [comment]
That's right! I've already modified the requirements.txt file.
